apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['request_id', 'user_id', 'character_id']
    version: 1
