"""increase_creature_cr_length

Revision ID: 897b7564919e
Revises: bc9493d1a8e0
Create Date: 2026-01-29 19:07:58.429841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897b7564919e'
down_revision = 'bc9493d1a8e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creatures', 'cr',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('creatures', 'xp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('xp', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('creatures', 'cr',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
