"""Add quest tracking system with objectives and character relationships

Revision ID: 8fdec8b4060e
Revises: a4353768274f
Create Date: 2026-01-03 15:44:28.641323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fdec8b4060e'
down_revision = 'a4353768274f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('condition', sa.Enum('Blinded', 'Charmed', 'Deafened', 'Frightened', 'Grappled', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Stunned', 'Unconscious', name='conditiontype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_conditions_character_id'), 'character_conditions', ['character_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('not_started', 'in_progress', 'completed', 'failed', name='queststate'), nullable=False),
    sa.Column('quest_giver_id', sa.UUID(), nullable=True),
    sa.Column('rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quest_giver_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_state'), 'quests', ['state'], unique=False)
    op.create_table('character_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_character_quest_unique', 'character_quests', ['character_id', 'quest_id'], unique=True)
    op.create_index(op.f('ix_character_quests_character_id'), 'character_quests', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_quests_quest_id'), 'character_quests', ['quest_id'], unique=False)
    op.create_table('quest_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_objectives_quest_id'), 'quest_objectives', ['quest_id'], unique=False)
    op.alter_column('character_spells', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_character_spells_character', table_name='character_spells')
    op.drop_index('ix_character_spells_unique', table_name='character_spells')
    op.create_index('ix_character_spells_char_spell', 'character_spells', ['character_id', 'spell_id'], unique=True)
    op.create_index(op.f('ix_character_spells_character_id'), 'character_spells', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_spells_spell_id'), 'character_spells', ['spell_id'], unique=False)
    
    # Add experience_points column with default value first
    op.add_column('characters', sa.Column('experience_points', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE characters SET experience_points = 0 WHERE experience_points IS NULL')
    # Make column non-nullable
    op.alter_column('characters', 'experience_points', nullable=False)
    
    op.alter_column('characters', 'character_type',
               existing_type=postgresql.ENUM('player', 'companion', 'npc', name='charactertype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'strength',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'dexterity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'constitution',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'intelligence',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'wisdom',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'charisma',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'carrying_capacity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'spell_slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    
    # Add started_at column to combat_encounters (replacing created_at)
    # Add with nullable first, set default, then make non-nullable
    op.add_column('combat_encounters', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE combat_encounters SET started_at = CURRENT_TIMESTAMP WHERE started_at IS NULL")
    op.alter_column('combat_encounters', 'started_at', nullable=False)
    
    op.drop_index('ix_combat_session_active', table_name='combat_encounters')
    op.drop_column('combat_encounters', 'created_at')
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('items', 'weight',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('items', 'value',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('items', 'equipped',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.alter_column('spells', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('spells', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('items', 'equipped',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('items', 'value',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('items', 'weight',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('combat_encounters', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_combat_session_active', 'combat_encounters', ['session_id', 'is_active'], unique=False)
    op.drop_column('combat_encounters', 'started_at')
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('characters', 'spell_slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('characters', 'carrying_capacity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('150'),
               existing_nullable=False)
    op.alter_column('characters', 'charisma',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'wisdom',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'intelligence',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'constitution',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'dexterity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'strength',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('characters', 'level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('characters', 'character_type',
               existing_type=postgresql.ENUM('player', 'companion', 'npc', name='charactertype'),
               server_default=sa.text("'player'::charactertype"),
               existing_nullable=False)
    op.drop_column('characters', 'experience_points')
    op.drop_index(op.f('ix_character_spells_spell_id'), table_name='character_spells')
    op.drop_index(op.f('ix_character_spells_character_id'), table_name='character_spells')
    op.drop_index('ix_character_spells_char_spell', table_name='character_spells')
    op.create_index('ix_character_spells_unique', 'character_spells', ['character_id', 'spell_id'], unique=True)
    op.create_index('ix_character_spells_character', 'character_spells', ['character_id'], unique=False)
    op.alter_column('character_spells', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_quest_objectives_quest_id'), table_name='quest_objectives')
    op.drop_table('quest_objectives')
    op.drop_index(op.f('ix_character_quests_quest_id'), table_name='character_quests')
    op.drop_index(op.f('ix_character_quests_character_id'), table_name='character_quests')
    op.drop_index('ix_character_quest_unique', table_name='character_quests')
    op.drop_table('character_quests')
    op.drop_index(op.f('ix_quests_state'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_character_conditions_character_id'), table_name='character_conditions')
    op.drop_table('character_conditions')
    # ### end Alembic commands ###
