"""add_scene_image_url_to_conversation_messages

Revision ID: 20260120_1547
Revises: 20260115_1658_22e12b76a7c3
Create Date: 2026-01-20 15:47:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260120_1547"
down_revision: Union[str, None] = "20260116_encounter"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation_messages", sa.Column("scene_image_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_messages", "scene_image_url")
    # ### end Alembic commands ###
