"""increase_item_catalog_rarity_length

Revision ID: 211662d3ad50
Revises: 91d0657d4733
Create Date: 2026-01-29 17:41:02.601571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211662d3ad50'
down_revision = '91d0657d4733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_catalog', 'rarity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_catalog', 'rarity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
