"""add_item_catalog_table

Revision ID: 91d0657d4733
Revises: 95aec39bb85c
Create Date: 2026-01-29 17:37:21.633955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91d0657d4733'
down_revision = '95aec39bb85c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('ac_base', sa.Integer(), nullable=True),
    sa.Column('ac_bonus', sa.Integer(), nullable=True),
    sa.Column('damage_dice', sa.String(length=20), nullable=True),
    sa.Column('damage_type', sa.String(length=20), nullable=True),
    sa.Column('versatile_damage', sa.String(length=20), nullable=True),
    sa.Column('attack_bonus', sa.Integer(), nullable=True),
    sa.Column('damage_bonus', sa.Integer(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_gp', sa.Integer(), nullable=True),
    sa.Column('cost_cp', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('book', sa.String(length=200), nullable=True),
    sa.Column('expansion', sa.Integer(), nullable=True),
    sa.Column('properties_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_catalog_category'), 'item_catalog', ['category'], unique=False)
    op.create_index(op.f('ix_item_catalog_id'), 'item_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_item_catalog_name'), 'item_catalog', ['name'], unique=True)
    op.create_index(op.f('ix_item_catalog_rarity'), 'item_catalog', ['rarity'], unique=False)
    op.drop_index(op.f('ix_generated_images_description_hash'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.drop_table('generated_images')
    op.alter_column('adventure_memories', 'event_type',
               existing_type=postgresql.ENUM('combat', 'dialogue', 'discovery', 'decision', 'quest', 'npc_interaction', 'loot', 'location', 'other', 'summary', name='eventtype'),
               type_=sa.Enum('combat', 'dialogue', 'discovery', 'decision', 'quest', 'npc_interaction', 'loot', 'location', 'summary', 'other', name='eventtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('character_conditions', 'condition',
               existing_type=postgresql.ENUM('Blinded', 'Charmed', 'Deafened', 'Frightened', 'Grappled', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Stunned', 'Unconscious', name='conditiontype'),
               type_=sa.Enum('Blinded', 'Charmed', 'Deafened', 'Frightened', 'Grappled', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Stunned', 'Unconscious', name='conditiontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('characters', 'character_type',
               existing_type=postgresql.ENUM('player', 'companion', 'npc', name='charactertype'),
               type_=sa.Enum('player', 'companion', 'npc', name='charactertype', native_enum=False),
               existing_nullable=False)
    op.alter_column('characters', 'character_class',
               existing_type=postgresql.ENUM('Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard', name='characterclass'),
               type_=sa.Enum('Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard', name='characterclass', native_enum=False),
               existing_nullable=False)
    op.alter_column('characters', 'race',
               existing_type=postgresql.ENUM('Dragonborn', 'Dwarf', 'Elf', 'Gnome', 'Half-Elf', 'Half-Orc', 'Halfling', 'Human', 'Tiefling', name='characterrace'),
               type_=sa.Enum('Dragonborn', 'Dwarf', 'Elf', 'Gnome', 'Half-Elf', 'Half-Orc', 'Halfling', 'Human', 'Tiefling', name='characterrace', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_companions_id'), 'companions', ['id'], unique=False)
    op.alter_column('conversation_messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               type_=sa.Enum('user', 'assistant', 'system', 'companion', name='messagerole', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_creatures_cr'), 'creatures', ['cr'], unique=False)
    op.alter_column('items', 'item_type',
               existing_type=postgresql.ENUM('weapon', 'armor', 'consumable', 'quest', 'misc', name='itemtype'),
               type_=sa.Enum('weapon', 'armor', 'consumable', 'quest', 'misc', name='itemtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('quests', 'state',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', 'failed', name='queststate'),
               type_=sa.Enum('not_started', 'in_progress', 'completed', 'failed', name='queststate', native_enum=False),
               existing_nullable=False)
    op.alter_column('spells', 'school',
               existing_type=postgresql.ENUM('Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', name='spellschool'),
               type_=sa.Enum('Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', name='spellschool', native_enum=False),
               existing_nullable=False)
    op.alter_column('spells', 'casting_time',
               existing_type=postgresql.ENUM('1 action', '1 bonus action', '1 reaction', '1 minute', '10 minutes', '1 hour', '1 minute (ritual)', name='castingtime'),
               type_=sa.Enum('1 action', '1 bonus action', '1 reaction', '1 minute', '10 minutes', '1 hour', '1 minute (ritual)', name='castingtime', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('spells_name_key'), 'spells', type_='unique')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_guest_token_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_guest_token'), table_name='users')
    op.create_index(op.f('ix_users_guest_token'), 'users', ['guest_token'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_guest_token'), table_name='users')
    op.create_index(op.f('ix_users_guest_token'), 'users', ['guest_token'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_guest_token_key'), 'users', ['guest_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_unique_constraint(op.f('spells_name_key'), 'spells', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('spells', 'casting_time',
               existing_type=sa.Enum('1 action', '1 bonus action', '1 reaction', '1 minute', '10 minutes', '1 hour', '1 minute (ritual)', name='castingtime', native_enum=False),
               type_=postgresql.ENUM('1 action', '1 bonus action', '1 reaction', '1 minute', '10 minutes', '1 hour', '1 minute (ritual)', name='castingtime'),
               existing_nullable=False)
    op.alter_column('spells', 'school',
               existing_type=sa.Enum('Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', name='spellschool', native_enum=False),
               type_=postgresql.ENUM('Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', name='spellschool'),
               existing_nullable=False)
    op.alter_column('quests', 'state',
               existing_type=sa.Enum('not_started', 'in_progress', 'completed', 'failed', name='queststate', native_enum=False),
               type_=postgresql.ENUM('not_started', 'in_progress', 'completed', 'failed', name='queststate'),
               existing_nullable=False)
    op.alter_column('items', 'item_type',
               existing_type=sa.Enum('weapon', 'armor', 'consumable', 'quest', 'misc', name='itemtype', native_enum=False),
               type_=postgresql.ENUM('weapon', 'armor', 'consumable', 'quest', 'misc', name='itemtype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_creatures_cr'), table_name='creatures')
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', 'system', 'companion', name='messagerole', native_enum=False),
               type_=postgresql.ENUM('user', 'assistant', 'system', name='messagerole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_companions_id'), table_name='companions')
    op.alter_column('characters', 'race',
               existing_type=sa.Enum('Dragonborn', 'Dwarf', 'Elf', 'Gnome', 'Half-Elf', 'Half-Orc', 'Halfling', 'Human', 'Tiefling', name='characterrace', native_enum=False),
               type_=postgresql.ENUM('Dragonborn', 'Dwarf', 'Elf', 'Gnome', 'Half-Elf', 'Half-Orc', 'Halfling', 'Human', 'Tiefling', name='characterrace'),
               existing_nullable=False)
    op.alter_column('characters', 'character_class',
               existing_type=sa.Enum('Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard', name='characterclass', native_enum=False),
               type_=postgresql.ENUM('Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Monk', 'Paladin', 'Ranger', 'Rogue', 'Sorcerer', 'Warlock', 'Wizard', name='characterclass'),
               existing_nullable=False)
    op.alter_column('characters', 'character_type',
               existing_type=sa.Enum('player', 'companion', 'npc', name='charactertype', native_enum=False),
               type_=postgresql.ENUM('player', 'companion', 'npc', name='charactertype'),
               existing_nullable=False)
    op.alter_column('character_conditions', 'condition',
               existing_type=sa.Enum('Blinded', 'Charmed', 'Deafened', 'Frightened', 'Grappled', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Stunned', 'Unconscious', name='conditiontype', native_enum=False),
               type_=postgresql.ENUM('Blinded', 'Charmed', 'Deafened', 'Frightened', 'Grappled', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Stunned', 'Unconscious', name='conditiontype'),
               existing_nullable=False)
    op.alter_column('adventure_memories', 'event_type',
               existing_type=sa.Enum('combat', 'dialogue', 'discovery', 'decision', 'quest', 'npc_interaction', 'loot', 'location', 'summary', 'other', name='eventtype', native_enum=False),
               type_=postgresql.ENUM('combat', 'dialogue', 'discovery', 'decision', 'quest', 'npc_interaction', 'loot', 'location', 'other', 'summary', name='eventtype'),
               existing_nullable=False)
    op.create_table('generated_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reuse_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_images_pkey'))
    )
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
    op.create_index(op.f('ix_generated_images_description_hash'), 'generated_images', ['description_hash'], unique=True)
    op.drop_index(op.f('ix_item_catalog_rarity'), table_name='item_catalog')
    op.drop_index(op.f('ix_item_catalog_name'), table_name='item_catalog')
    op.drop_index(op.f('ix_item_catalog_id'), table_name='item_catalog')
    op.drop_index(op.f('ix_item_catalog_category'), table_name='item_catalog')
    op.drop_table('item_catalog')
    # ### end Alembic commands ###
