"""add_active_effects_table

Revision ID: a1b2c3d4e5f6
Revises: 2863670d6afc
Create Date: 2026-01-30 00:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "2863670d6afc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_effects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("effect_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("source_character_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("duration_type", sa.String(length=50), nullable=False),
        sa.Column("duration_value", sa.Integer(), nullable=True),
        sa.Column("rounds_remaining", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("bonus_value", sa.Integer(), nullable=True),
        sa.Column("dice_bonus", sa.String(length=20), nullable=True),
        sa.Column("advantage", sa.Boolean(), nullable=True),
        sa.Column("disadvantage", sa.Boolean(), nullable=True),
        sa.Column("stacks", sa.Boolean(), nullable=True),
        sa.Column("stack_count", sa.Integer(), nullable=True),
        sa.Column("requires_concentration", sa.Boolean(), nullable=True),
        sa.Column("concentration_dc", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["game_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_active_effects_character_id"), "active_effects", ["character_id"], unique=False
    )
    op.create_index(op.f("ix_active_effects_id"), "active_effects", ["id"], unique=False)
    op.create_index(
        op.f("ix_active_effects_is_active"), "active_effects", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_active_effects_session_id"), "active_effects", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_active_effects_session_id"), table_name="active_effects")
    op.drop_index(op.f("ix_active_effects_is_active"), table_name="active_effects")
    op.drop_index(op.f("ix_active_effects_id"), table_name="active_effects")
    op.drop_index(op.f("ix_active_effects_character_id"), table_name="active_effects")
    op.drop_table("active_effects")
    # ### end Alembic commands ###
