"""API v1 endpoints - individual routers are combined in router.py"""

from . import (
    adventures,
    auth,
    characters,
    combat,
    companions,
    conditions,
    conversations,
    creatures,
    dice,
    effects,
    game,
    images,
    inventory,
    items,
    loot,
    memories,
    npcs,
    progression,
    quests,
    random_status,
    rest,
    rules,
    sessions,
    spells,
)

__all__ = [
    "adventures",
    "auth",
    "characters",
    "combat",
    "companions",
    "conditions",
    "conversations",
    "creatures",
    "dice",
    "effects",
    "game",
    "images",
    "inventory",
    "items",
    "loot",
    "memories",
    "npcs",
    "progression",
    "quests",
    "random_status",
    "rest",
    "rules",
    "sessions",
    "spells",
]
